name: Build

on:
  push:
    branches: [ main ]

jobs:
  Build:

    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v4.1.4
    - uses: actions/checkout@v4.1.4
      with:
        repository: SMGCommunity/Syati
        path: Syati
    - uses: actions/checkout@v4.1.4
      with:
        repository: SMGCommunity/SyatiModuleBuildTool
        path: SyatiModuleBuildTool
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - shell: cmd
      working-directory: SyatiModuleBuildTool
      run: dotnet build -c Release
    - shell: cmd
      run: |
        mkdir out
        mklink SyatiModuleBuildTool.exe SyatiModuleBuildTool\SyatiModuleBuildTool\bin\Release\net8.0\SyatiModuleBuildTool.exe
        mklink SyatiModuleBuildTool.dll SyatiModuleBuildTool\SyatiModuleBuildTool\bin\Release\net8.0\SyatiModuleBuildTool.dll
        mklink SyatiModuleBuildTool.runtimeconfig.json SyatiModuleBuildTool\SyatiModuleBuildTool\bin\Release\net8.0\SyatiModuleBuildTool.runtimeconfig.json
    - shell: cmd
      working-directory: Syati/deps
      run: |
       curl -k -L -O https://github.com/Lord-Giganticus/SyatiSetup/releases/download/Auto/syatisetup.exe
       syatisetup.exe
       rd /s /q Kamek
       curl -k -L -O https://github.com/Treeki/Kamek/releases/download/2024-04-10_prerelease/kamek_2024-04-10_win-x64.zip
       7z x kamek_2024-04-10_win-x64.zip -oKamek
    - shell: cmd
      run: |
         SyatiModuleBuildTool.exe USA Syati modules out
         SyatiModuleBuildTool.exe PAL Syati modules out
         SyatiModuleBuildTool.exe JPN Syati modules out
    - uses: actions/upload-artifact@v4.3.3
      with:
        path: out/*.bin
        name: Build